name: Build-Release-Publish

on:
  push:
    branches:
      - master

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  NUGET_XMLDOC_MODE: skip
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.check-tag.outputs.exists }}
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Get version
        id: get-version
        shell: pwsh
        run: |
          $doc = [XML](Get-Content 'Base32768/Base32768.csproj')
          echo "::set-output name=version::$(([string]$doc.Project.PropertyGroup.Version).Trim())"
      - name: Check tag
        uses: mukunku/tag-exists-action@v1.0.0
        id: check-tag
        with:
          tag: ${{ steps.get-version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo " exists? -- ${{ steps.check-tag.outputs.exists }}"

  new-version-only:
    runs-on: ubuntu-latest
    needs: [get-version]
    if: ${{ needs.get-version.outputs.exists == 'false' }}
    steps:
      - run: echo "new version-> ${{ needs.get-version.outputs.version }}"

  build:
    runs-on: ubuntu-latest
    needs: [new-version-only]
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Test
        run: dotnet test --no-restore --verbosity normal -c Release
      - uses: actions/upload-artifact@v1
        with:
          name: dist
          path: Base32768/bin/Packages/Release

  release:
    runs-on: ubuntu-latest
    needs: [get-version, build]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Push tag
        id: tag-version
        uses: mathieudutour/github-tag-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ needs.get-version.outputs.version }}
          tag_prefix: ""
      - name: Create release
        uses: ncipollo/release-action@v1
        id: create-release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.tag-version.outputs.new_tag }}
          name: Version ${{ needs.get-version.outputs.version }}
          body: ${{ steps.tag_version.outputs.changelog }}
          artifacts: "./dist/*.nupkg"

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Upload nuget
        run: dotnet nuget push "./dist/*.nupkg" --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_KEY }}