name: test

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  NUGET_XMLDOC_MODE: skip
  WORKFLOW_BUILD_SLN: Base32768.sln

jobs:
  format:
    uses: kzrnm/dotnet-actions/.github/workflows/format.yml@v1
    with:
      target: Base32768.sln
      dotnet-version: 6.0.x
  test:
    uses: kzrnm/dotnet-actions/.github/workflows/unittest.yml@v1
    with:
      target: Base32768.sln
      dotnet-version: 6.0.x
      test-logger: GitHubActions
